"""initial

Revision ID: 77c8cddd0f12
Revises: 
Create Date: 2026-02-13 15:30:40.163018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c8cddd0f12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('agency', sa.String(length=200), nullable=True),
    sa.Column('agency_code', sa.String(length=20), nullable=True),
    sa.Column('program_name', sa.String(length=300), nullable=True),
    sa.Column('amount_floor', sa.Integer(), nullable=True),
    sa.Column('amount_ceiling', sa.Integer(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('is_rolling', sa.Boolean(), nullable=True),
    sa.Column('eligible_applicant_types', sa.JSON(), nullable=True),
    sa.Column('eligible_categories', sa.JSON(), nullable=True),
    sa.Column('cfda_numbers', sa.JSON(), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('geographic_scope', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('grants_fetched', sa.Integer(), nullable=True),
    sa.Column('grants_new', sa.Integer(), nullable=True),
    sa.Column('grants_updated', sa.Integer(), nullable=True),
    sa.Column('grants_closed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('organization_name', sa.String(length=300), nullable=True),
    sa.Column('organization_ein', sa.String(length=12), nullable=True),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('mission_statement', sa.Text(), nullable=False),
    sa.Column('focus_areas', sa.JSON(), nullable=False),
    sa.Column('annual_budget', sa.String(length=20), nullable=True),
    sa.Column('employee_count', sa.String(length=20), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('geographic_focus', sa.JSON(), nullable=True),
    sa.Column('eligibility_attributes', sa.JSON(), nullable=True),
    sa.Column('funding_preferences', sa.JSON(), nullable=True),
    sa.Column('email_preferences', sa.JSON(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('match_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('grant_id', sa.String(length=36), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('grant_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('semantic_similarity', sa.Float(), nullable=False),
    sa.Column('eligibility_bonus', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('grant_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('remind_days_before', sa.Integer(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked_grants')
    op.drop_table('match_results')
    op.drop_table('match_feedback')
    op.drop_table('users')
    op.drop_table('ingestion_runs')
    op.drop_table('grants')
    # ### end Alembic commands ###
