"""add embedding fields to grants

Revision ID: a8c119f956ee
Revises: 77c8cddd0f12
Create Date: 2026-02-13 15:41:38.178030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c119f956ee'
down_revision: Union[str, Sequence[str], None] = '77c8cddd0f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('embedding_data', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grants', 'embedding_model')
    op.drop_column('grants', 'embedding_data')
    # ### end Alembic commands ###
